### ISSUE TITLE
Error could not find gem `sass-embedded' when executing bundle

### ISSUE THREAD

**Issue by bubl-ai** [cotes2020/jekyll-theme-chirpy#1533]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When executing `bundle` within my folder I get the next error.
```
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Resolving dependencies...
Could not find gems matching 'sass-embedded' valid for all resolution platforms
(aarch64-linux-musl, arm-linux, x86_64-linux-musl, arm-linux-musleabihf,
x86-linux, x86_64-linux, arm64-darwin, x86-linux-musl, x86_64-darwin) in
rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'sass-embedded':
  * sass-embedded-0.1.0
  * sass-embedded-0.1.1
  * sass-embedded-0.1.2
  * sass-embedded-0.1.3
  * sass-embedded-0.2.1
  * sass-embedded-0.2.2
  * sass-embedded-0.2.3
  * sass-embedded-0.2.4
  * sass-embedded-0.3.0
  * sass-embedded-0.4.0
  * sass-embedded-0.4.1
  * sass-embedded-0.4.2
  * sass-embedded-0.5.0
  * sass-embedded-0.6.0
  * sass-embedded-0.6.1
  * sass-embedded-0.6.2
  * sass-embedded-0.6.3
  * sass-embedded-0.6.4
  * sass-embedded-0.6.5
  * sass-embedded-0.6.6
  * sass-embedded-0.6.7
  * sass-embedded-0.7.0
  * sass-embedded-0.7.1
  * sass-embedded-0.7.2
  * sass-embedded-0.7.3
  * sass-embedded-0.7.4
  * sass-embedded-0.7.5
  * sass-embedded-0.7.6
  * sass-embedded-0.7.7
  * sass-embedded-0.7.8
  * sass-embedded-0.7.9
  * sass-embedded-0.7.10
  * sass-embedded-0.7.11
  * sass-embedded-0.7.12
  * sass-embedded-0.7.13
  * sass-embedded-0.7.14
  * sass-embedded-0.7.15
  * sass-embedded-0.7.16
  * sass-embedded-0.7.17
  * sass-embedded-0.7.18
  * sass-embedded-0.7.19
  * sass-embedded-0.7.20
  * sass-embedded-0.7.21
  * sass-embedded-0.7.22
  * sass-embedded-0.7.23
  * sass-embedded-0.7.24
  * sass-embedded-0.7.25
  * sass-embedded-0.7.26
  * sass-embedded-0.7.27
  * sass-embedded-0.7.28
  * sass-embedded-0.8.0
  * sass-embedded-0.8.1
  * sass-embedded-0.8.2
  * sass-embedded-0.9.0
  * sass-embedded-0.9.1
  * sass-embedded-0.9.2
  * sass-embedded-0.9.3
  * sass-embedded-0.10.0
  * sass-embedded-0.11.0
  * sass-embedded-0.12.0
  * sass-embedded-0.13.0
  * sass-embedded-0.13.1
  * sass-embedded-0.13.2
  * sass-embedded-0.13.3
  * sass-embedded-0.13.4
  * sass-embedded-0.14.0
  * sass-embedded-0.15.0
  * sass-embedded-0.16.0
  * sass-embedded-0.16.1
  * sass-embedded-0.16.2
  * sass-embedded-0.17.0
  * sass-embedded-0.18.0
  * sass-embedded-0.18.1
  * sass-embedded-0.18.2
  * sass-embedded-0.18.3
  * sass-embedded-0.18.4
  * sass-embedded-0.19.0
  * sass-embedded-0.19.1
  * sass-embedded-0.19.2
  * sass-embedded-0.19.3
  * sass-embedded-0.19.4
  * sass-embedded-0.19.5
  * sass-embedded-0.19.6
  * sass-embedded-0.19.7
  * sass-embedded-1.0.0
  * sass-embedded-1.0.1
  * sass-embedded-1.0.2
  * sass-embedded-1.0.3
  * sass-embedded-1.0.4
  * sass-embedded-1.0.5
  * sass-embedded-1.0.6
  * sass-embedded-1.0.7
  * sass-embedded-1.0.8
  * sass-embedded-1.0.9
  * sass-embedded-1.0.10
  * sass-embedded-1.0.11
  * sass-embedded-1.0.12
  * sass-embedded-1.0.13
  * sass-embedded-1.0.14
  * sass-embedded-1.0.15
  * sass-embedded-1.0.16
  * sass-embedded-1.0.17
  * sass-embedded-1.0.18
  * sass-embedded-1.0.19
  * sass-embedded-1.0.20
  * sass-embedded-1.0.21
  * sass-embedded-1.1.0
  * sass-embedded-1.1.1
  * sass-embedded-1.1.2
  * sass-embedded-1.2.0
  * sass-embedded-1.2.1
  * sass-embedded-1.2.2
  * sass-embedded-1.2.3
  * sass-embedded-1.2.4
  * sass-embedded-1.2.5
  * sass-embedded-1.2.6
  * sass-embedded-1.2.7
  * sass-embedded-1.2.8
  * sass-embedded-1.2.9
  * sass-embedded-1.3.0
  * sass-embedded-1.3.1
  * sass-embedded-1.3.2
  * sass-embedded-1.4.0
  * sass-embedded-1.4.1
  * sass-embedded-1.4.2
  * sass-embedded-1.4.3
  * sass-embedded-1.4.4
  * sass-embedded-1.5.0
  * sass-embedded-1.6.0
  * sass-embedded-1.6.1
  * sass-embedded-1.6.2
  * sass-embedded-1.53.0
  * sass-embedded-1.54.0
  * sass-embedded-1.54.2
  * sass-embedded-1.54.3
  * sass-embedded-1.54.4
  * sass-embedded-1.54.5
  * sass-embedded-1.54.6-arm64-darwin
  * sass-embedded-1.54.6
  * sass-embedded-1.54.6-x64-mingw-ucrt
  * sass-embedded-1.54.6-x64-mingw32
  * sass-embedded-1.54.6-x86-mingw32
  * sass-embedded-1.54.6-x86_64-darwin
  * sass-embedded-1.54.7-aarch64-linux
  * sass-embedded-1.54.7-arm-linux
  * sass-embedded-1.54.7-arm64-darwin
  * sass-embedded-1.54.7
  * sass-embedded-1.54.7-x64-mingw-ucrt
  * sass-embedded-1.54.7-x64-mingw32
  * sass-embedded-1.54.7-x86-linux
  * sass-embedded-1.54.7-x86-mingw32
  * sass-embedded-1.54.7-x86_64-darwin
  * sass-embedded-1.54.7-x86_64-linux
  * sass-embedded-1.54.8-aarch64-linux
  * sass-embedded-1.54.8-arm-linux
  * sass-embedded-1.54.8-arm64-darwin
  * sass-embedded-1.54.8
  * sass-embedded-1.54.8-x64-mingw-ucrt
  * sass-embedded-1.54.8-x64-mingw32
  * sass-embedded-1.54.8-x86-linux
  * sass-embedded-1.54.8-x86-mingw32
  * sass-embedded-1.54.8-x86_64-darwin
  * sass-embedded-1.54.8-x86_64-linux
  * sass-embedded-1.54.9-aarch64-linux
  * sass-embedded-1.54.9-arm-linux
  * sass-embedded-1.54.9-arm64-darwin
  * sass-embedded-1.54.9
  * sass-embedded-1.54.9-x64-mingw-ucrt
  * sass-embedded-1.54.9-x64-mingw32
  * sass-embedded-1.54.9-x86-linux
  * sass-embedded-1.54.9-x86-mingw32
  * sass-embedded-1.54.9-x86_64-darwin
  * sass-embedded-1.54.9-x86_64-linux
  * sass-embedded-1.55.0-aarch64-linux
  * sass-embedded-1.55.0-arm-linux
  * sass-embedded-1.55.0-arm64-darwin
  * sass-embedded-1.55.0
  * sass-embedded-1.55.0-x64-mingw-ucrt
  * sass-embedded-1.55.0-x64-mingw32
  * sass-embedded-1.55.0-x86-linux
  * sass-embedded-1.55.0-x86-mingw32
  * sass-embedded-1.55.0-x86_64-darwin
  * sass-embedded-1.55.0-x86_64-linux
  * sass-embedded-1.56.1-aarch64-linux
  * sass-embedded-1.56.1-arm-linux
  * sass-embedded-1.56.1-arm64-darwin
  * sass-embedded-1.56.1
  * sass-embedded-1.56.1-x64-mingw-ucrt
  * sass-embedded-1.56.1-x64-mingw32
  * sass-embedded-1.56.1-x86-linux
  * sass-embedded-1.56.1-x86-mingw32
  * sass-embedded-1.56.1-x86_64-darwin
  * sass-embedded-1.56.1-x86_64-linux
  * sass-embedded-1.56.2-aarch64-linux
  * sass-embedded-1.56.2-arm-linux
  * sass-embedded-1.56.2-arm64-darwin
  * sass-embedded-1.56.2
  * sass-embedded-1.56.2-x64-mingw-ucrt
  * sass-embedded-1.56.2-x64-mingw32
  * sass-embedded-1.56.2-x86-linux
  * sass-embedded-1.56.2-x86-mingw32
  * sass-embedded-1.56.2-x86_64-darwin
  * sass-embedded-1.56.2-x86_64-linux
  * sass-embedded-1.57.1-aarch64-linux
  * sass-embedded-1.57.1-arm-linux
  * sass-embedded-1.57.1-arm64-darwin
  * sass-embedded-1.57.1
  * sass-embedded-1.57.1-x64-mingw-ucrt
  * sass-embedded-1.57.1-x64-mingw32
  * sass-embedded-1.57.1-x86-linux
  * sass-embedded-1.57.1-x86-mingw32
  * sass-embedded-1.57.1-x86_64-darwin
  * sass-embedded-1.57.1-x86_64-linux
  * sass-embedded-1.58.0-aarch64-linux
  * sass-embedded-1.58.0-aarch64-linux-musl
  * sass-embedded-1.58.0-arm-linux
  * sass-embedded-1.58.0-arm-linux-musleabihf
  * sass-embedded-1.58.0-arm64-darwin
  * sass-embedded-1.58.0
  * sass-embedded-1.58.0-x64-mingw-ucrt
  * sass-embedded-1.58.0-x64-mingw32
  * sass-embedded-1.58.0-x86-linux
  * sass-embedded-1.58.0-x86-linux-musl
  * sass-embedded-1.58.0-x86-mingw32
  * sass-embedded-1.58.0-x86_64-darwin
  * sass-embedded-1.58.0-x86_64-linux
  * sass-embedded-1.58.0-x86_64-linux-musl
  * sass-embedded-1.58.2-aarch64-linux
  * sass-embedded-1.58.2-aarch64-linux-musl
  * sass-embedded-1.58.2-arm-linux
  * sass-embedded-1.58.2-arm-linux-musleabihf
  * sass-embedded-1.58.2-arm64-darwin
  * sass-embedded-1.58.2
  * sass-embedded-1.58.2-x64-mingw-ucrt
  * sass-embedded-1.58.2-x64-mingw32
  * sass-embedded-1.58.2-x86-linux
  * sass-embedded-1.58.2-x86-linux-musl
  * sass-embedded-1.58.2-x86-mingw32
  * sass-embedded-1.58.2-x86_64-darwin
  * sass-embedded-1.58.2-x86_64-linux
  * sass-embedded-1.58.2-x86_64-linux-musl
  * sass-embedded-1.58.3-aarch64-linux
  * sass-embedded-1.58.3-aarch64-linux-android
  * sass-embedded-1.58.3-aarch64-linux-musl
  * sass-embedded-1.58.3-arm-linux
  * sass-embedded-1.58.3-arm-linux-androideabi
  * sass-embedded-1.58.3-arm-linux-musleabihf
  * sass-embedded-1.58.3-arm64-darwin
  * sass-embedded-1.58.3
  * sass-embedded-1.58.3-x64-mingw-ucrt
  * sass-embedded-1.58.3-x64-mingw32
  * sass-embedded-1.58.3-x86-linux
  * sass-embedded-1.58.3-x86-linux-android
  * sass-embedded-1.58.3-x86-linux-musl
  * sass-embedded-1.58.3-x86-mingw32
  * sass-embedded-1.58.3-x86_64-darwin
  * sass-embedded-1.58.3-x86_64-linux
  * sass-embedded-1.58.3-x86_64-linux-android
  * sass-embedded-1.58.3-x86_64-linux-musl
  * sass-embedded-1.59.2-aarch64-linux
  * sass-embedded-1.59.2-aarch64-linux-android
  * sass-embedded-1.59.2-aarch64-linux-musl
  * sass-embedded-1.59.2-arm-linux
  * sass-embedded-1.59.2-arm-linux-androideabi
  * sass-embedded-1.59.2-arm-linux-musleabihf
  * sass-embedded-1.59.2-arm64-darwin
  * sass-embedded-1.59.2
  * sass-embedded-1.59.2-x64-mingw-ucrt
  * sass-embedded-1.59.2-x64-mingw32
  * sass-embedded-1.59.2-x86-linux
  * sass-embedded-1.59.2-x86-linux-android
  * sass-embedded-1.59.2-x86-linux-musl
  * sass-embedded-1.59.2-x86-mingw32
  * sass-embedded-1.59.2-x86_64-darwin
  * sass-embedded-1.59.2-x86_64-linux
  * sass-embedded-1.59.2-x86_64-linux-android
  * sass-embedded-1.59.2-x86_64-linux-musl
  * sass-embedded-1.59.3-aarch64-linux
  * sass-embedded-1.59.3-aarch64-linux-android
  * sass-embedded-1.59.3-aarch64-linux-musl
  * sass-embedded-1.59.3-arm-linux
  * sass-embedded-1.59.3-arm-linux-androideabi
  * sass-embedded-1.59.3-arm-linux-musleabihf
  * sass-embedded-1.59.3-arm64-darwin
  * sass-embedded-1.59.3
  * sass-embedded-1.59.3-x64-mingw-ucrt
  * sass-embedded-1.59.3-x64-mingw32
  * sass-embedded-1.59.3-x86-linux
  * sass-embedded-1.59.3-x86-linux-android
  * sass-embedded-1.59.3-x86-linux-musl
  * sass-embedded-1.59.3-x86-mingw32
  * sass-embedded-1.59.3-x86_64-darwin
  * sass-embedded-1.59.3-x86_64-linux
  * sass-embedded-1.59.3-x86_64-linux-android
  * sass-embedded-1.59.3-x86_64-linux-musl
  * sass-embedded-1.60.0-aarch64-linux
  * sass-embedded-1.60.0-aarch64-linux-android
  * sass-embedded-1.60.0-aarch64-linux-musl
  * sass-embedded-1.60.0-arm-linux
  * sass-embedded-1.60.0-arm-linux-androideabi
  * sass-embedded-1.60.0-arm-linux-musleabihf
  * sass-embedded-1.60.0-arm64-darwin
  * sass-embedded-1.60.0
  * sass-embedded-1.60.0-x64-mingw-ucrt
  * sass-embedded-1.60.0-x64-mingw32
  * sass-embedded-1.60.0-x86-linux
  * sass-embedded-1.60.0-x86-linux-android
  * sass-embedded-1.60.0-x86-linux-musl
  * sass-embedded-1.60.0-x86-mingw32
  * sass-embedded-1.60.0-x86_64-darwin
  * sass-embedded-1.60.0-x86_64-linux
  * sass-embedded-1.60.0-x86_64-linux-android
  * sass-embedded-1.60.0-x86_64-linux-musl
  * sass-embedded-1.61.0-aarch64-linux
  * sass-embedded-1.61.0-aarch64-linux-android
  * sass-embedded-1.61.0-aarch64-linux-musl
  * sass-embedded-1.61.0-arm-linux
  * sass-embedded-1.61.0-arm-linux-androideabi
  * sass-embedded-1.61.0-arm-linux-musleabihf
  * sass-embedded-1.61.0-arm64-darwin
  * sass-embedded-1.61.0
  * sass-embedded-1.61.0-x64-mingw-ucrt
  * sass-embedded-1.61.0-x64-mingw32
  * sass-embedded-1.61.0-x86-linux
  * sass-embedded-1.61.0-x86-linux-android
  * sass-embedded-1.61.0-x86-linux-musl
  * sass-embedded-1.61.0-x86-mingw32
  * sass-embedded-1.61.0-x86_64-darwin
  * sass-embedded-1.61.0-x86_64-linux
  * sass-embedded-1.61.0-x86_64-linux-android
  * sass-embedded-1.61.0-x86_64-linux-musl
  * sass-embedded-1.62.0-aarch64-linux
  * sass-embedded-1.62.0-aarch64-linux-android
  * sass-embedded-1.62.0-aarch64-linux-musl
  * sass-embedded-1.62.0-arm-linux
  * sass-embedded-1.62.0-arm-linux-androideabi
  * sass-embedded-1.62.0-arm-linux-musleabihf
  * sass-embedded-1.62.0-arm64-darwin
  * sass-embedded-1.62.0
  * sass-embedded-1.62.0-x64-mingw-ucrt
  * sass-embedded-1.62.0-x64-mingw32
  * sass-embedded-1.62.0-x86-linux
  * sass-embedded-1.62.0-x86-linux-android
  * sass-embedded-1.62.0-x86-linux-musl
  * sass-embedded-1.62.0-x86-mingw32
  * sass-embedded-1.62.0-x86_64-darwin
  * sass-embedded-1.62.0-x86_64-linux
  * sass-embedded-1.62.0-x86_64-linux-android
  * sass-embedded-1.62.0-x86_64-linux-musl
  * sass-embedded-1.62.1-aarch64-linux
  * sass-embedded-1.62.1-aarch64-linux-android
  * sass-embedded-1.62.1-aarch64-linux-musl
  * sass-embedded-1.62.1-arm-linux
  * sass-embedded-1.62.1-arm-linux-androideabi
  * sass-embedded-1.62.1-arm-linux-musleabihf
  * sass-embedded-1.62.1-arm64-darwin
  * sass-embedded-1.62.1
  * sass-embedded-1.62.1-x64-mingw-ucrt
  * sass-embedded-1.62.1-x64-mingw32
  * sass-embedded-1.62.1-x86-linux
  * sass-embedded-1.62.1-x86-linux-android
  * sass-embedded-1.62.1-x86-linux-musl
  * sass-embedded-1.62.1-x86-mingw32
  * sass-embedded-1.62.1-x86_64-darwin
  * sass-embedded-1.62.1-x86_64-linux
  * sass-embedded-1.62.1-x86_64-linux-android
  * sass-embedded-1.62.1-x86_64-linux-musl
  * sass-embedded-1.63.1-aarch64-linux
  * sass-embedded-1.63.1-aarch64-linux-android
  * sass-embedded-1.63.1-aarch64-linux-musl
  * sass-embedded-1.63.1-arm-linux
  * sass-embedded-1.63.1-arm-linux-androideabi
  * sass-embedded-1.63.1-arm-linux-musleabihf
  * sass-embedded-1.63.1-arm64-darwin
  * sass-embedded-1.63.1
  * sass-embedded-1.63.1-x64-mingw-ucrt
  * sass-embedded-1.63.1-x64-mingw32
  * sass-embedded-1.63.1-x86-linux
  * sass-embedded-1.63.1-x86-linux-android
  * sass-embedded-1.63.1-x86-linux-musl
  * sass-embedded-1.63.1-x86-mingw32
  * sass-embedded-1.63.1-x86_64-darwin
  * sass-embedded-1.63.1-x86_64-linux
  * sass-embedded-1.63.1-x86_64-linux-android
  * sass-embedded-1.63.1-x86_64-linux-musl
  * sass-embedded-1.63.2-aarch64-linux
  * sass-embedded-1.63.2-aarch64-linux-android
  * sass-embedded-1.63.2-aarch64-linux-musl
  * sass-embedded-1.63.2-arm-linux
  * sass-embedded-1.63.2-arm-linux-androideabi
  * sass-embedded-1.63.2-arm-linux-musleabihf
  * sass-embedded-1.63.2-arm64-darwin
  * sass-embedded-1.63.2
  * sass-embedded-1.63.2-x64-mingw-ucrt
  * sass-embedded-1.63.2-x64-mingw32
  * sass-embedded-1.63.2-x86-linux
  * sass-embedded-1.63.2-x86-linux-android
  * sass-embedded-1.63.2-x86-linux-musl
  * sass-embedded-1.63.2-x86-mingw32
  * sass-embedded-1.63.2-x86_64-darwin
  * sass-embedded-1.63.2-x86_64-linux
  * sass-embedded-1.63.2-x86_64-linux-android
  * sass-embedded-1.63.2-x86_64-linux-musl
  * sass-embedded-1.63.3-aarch64-linux
  * sass-embedded-1.63.3-aarch64-linux-android
  * sass-embedded-1.63.3-aarch64-linux-musl
  * sass-embedded-1.63.3-arm-linux
  * sass-embedded-1.63.3-arm-linux-androideabi
  * sass-embedded-1.63.3-arm-linux-musleabihf
  * sass-embedded-1.63.3-arm64-darwin
  * sass-embedded-1.63.3
  * sass-embedded-1.63.3-x64-mingw-ucrt
  * sass-embedded-1.63.3-x64-mingw32
  * sass-embedded-1.63.3-x86-linux
  * sass-embedded-1.63.3-x86-linux-android
  * sass-embedded-1.63.3-x86-linux-musl
  * sass-embedded-1.63.3-x86-mingw32
  * sass-embedded-1.63.3-x86_64-darwin
  * sass-embedded-1.63.3-x86_64-linux
  * sass-embedded-1.63.3-x86_64-linux-android
  * sass-embedded-1.63.3-x86_64-linux-musl
  * sass-embedded-1.63.4-aarch64-linux
  * sass-embedded-1.63.4-aarch64-linux-android
  * sass-embedded-1.63.4-aarch64-linux-musl
  * sass-embedded-1.63.4-arm-linux
  * sass-embedded-1.63.4-arm-linux-androideabi
  * sass-embedded-1.63.4-arm-linux-musleabihf
  * sass-embedded-1.63.4-arm64-darwin
  * sass-embedded-1.63.4
  * sass-embedded-1.63.4-x64-mingw-ucrt
  * sass-embedded-1.63.4-x64-mingw32
  * sass-embedded-1.63.4-x86-linux
  * sass-embedded-1.63.4-x86-linux-android
  * sass-embedded-1.63.4-x86-linux-musl
  * sass-embedded-1.63.4-x86-mingw32
  * sass-embedded-1.63.4-x86_64-darwin
  * sass-embedded-1.63.4-x86_64-linux
  * sass-embedded-1.63.4-x86_64-linux-android
  * sass-embedded-1.63.4-x86_64-linux-musl
  * sass-embedded-1.63.5-aarch64-linux
  * sass-embedded-1.63.5-aarch64-linux-android
  * sass-embedded-1.63.5-aarch64-linux-musl
  * sass-embedded-1.63.5-arm-linux
  * sass-embedded-1.63.5-arm-linux-androideabi
  * sass-embedded-1.63.5-arm-linux-musleabihf
  * sass-embedded-1.63.5-arm64-darwin
  * sass-embedded-1.63.5
  * sass-embedded-1.63.5-x64-mingw-ucrt
  * sass-embedded-1.63.5-x64-mingw32
  * sass-embedded-1.63.5-x86-linux
  * sass-embedded-1.63.5-x86-linux-android
  * sass-embedded-1.63.5-x86-linux-musl
  * sass-embedded-1.63.5-x86-mingw32
  * sass-embedded-1.63.5-x86_64-darwin
  * sass-embedded-1.63.5-x86_64-linux
  * sass-embedded-1.63.5-x86_64-linux-android
  * sass-embedded-1.63.5-x86_64-linux-musl
  * sass-embedded-1.63.6-aarch64-linux
  * sass-embedded-1.63.6-aarch64-linux-android
  * sass-embedded-1.63.6-aarch64-linux-musl
  * sass-embedded-1.63.6-arm-linux
  * sass-embedded-1.63.6-arm-linux-androideabi
  * sass-embedded-1.63.6-arm-linux-musleabihf
  * sass-embedded-1.63.6-arm64-darwin
  * sass-embedded-1.63.6
  * sass-embedded-1.63.6-x64-mingw-ucrt
  * sass-embedded-1.63.6-x64-mingw32
  * sass-embedded-1.63.6-x86-linux
  * sass-embedded-1.63.6-x86-linux-android
  * sass-embedded-1.63.6-x86-linux-musl
  * sass-embedded-1.63.6-x86-mingw32
  * sass-embedded-1.63.6-x86_64-darwin
  * sass-embedded-1.63.6-x86_64-linux
  * sass-embedded-1.63.6-x86_64-linux-android
  * sass-embedded-1.63.6-x86_64-linux-musl
  * sass-embedded-1.64.0-aarch64-linux
  * sass-embedded-1.64.0-aarch64-linux-android
  * sass-embedded-1.64.0-aarch64-linux-musl
  * sass-embedded-1.64.0-arm-linux
  * sass-embedded-1.64.0-arm-linux-androideabi
  * sass-embedded-1.64.0-arm-linux-musleabihf
  * sass-embedded-1.64.0-arm64-darwin
  * sass-embedded-1.64.0
  * sass-embedded-1.64.0-x64-mingw-ucrt
  * sass-embedded-1.64.0-x64-mingw32
  * sass-embedded-1.64.0-x86-linux
  * sass-embedded-1.64.0-x86-linux-android
  * sass-embedded-1.64.0-x86-linux-musl
  * sass-embedded-1.64.0-x86-mingw32
  * sass-embedded-1.64.0-x86_64-darwin
  * sass-embedded-1.64.0-x86_64-linux
  * sass-embedded-1.64.0-x86_64-linux-android
  * sass-embedded-1.64.0-x86_64-linux-musl
  * sass-embedded-1.64.1-aarch64-linux
  * sass-embedded-1.64.1-aarch64-linux-android
  * sass-embedded-1.64.1-aarch64-linux-musl
  * sass-embedded-1.64.1-arm-linux
  * sass-embedded-1.64.1-arm-linux-androideabi
  * sass-embedded-1.64.1-arm-linux-musleabihf
  * sass-embedded-1.64.1-arm64-darwin
  * sass-embedded-1.64.1
  * sass-embedded-1.64.1-x64-mingw-ucrt
  * sass-embedded-1.64.1-x64-mingw32
  * sass-embedded-1.64.1-x86-linux
  * sass-embedded-1.64.1-x86-linux-android
  * sass-embedded-1.64.1-x86-linux-musl
  * sass-embedded-1.64.1-x86-mingw32
  * sass-embedded-1.64.1-x86_64-darwin
  * sass-embedded-1.64.1-x86_64-linux
  * sass-embedded-1.64.1-x86_64-linux-android
  * sass-embedded-1.64.1-x86_64-linux-musl
  * sass-embedded-1.64.2-aarch64-linux
  * sass-embedded-1.64.2-aarch64-linux-android
  * sass-embedded-1.64.2-aarch64-linux-musl
  * sass-embedded-1.64.2-arm-linux
  * sass-embedded-1.64.2-arm-linux-androideabi
  * sass-embedded-1.64.2-arm-linux-musleabihf
  * sass-embedded-1.64.2-arm64-darwin
  * sass-embedded-1.64.2
  * sass-embedded-1.64.2-x64-mingw-ucrt
  * sass-embedded-1.64.2-x64-mingw32
  * sass-embedded-1.64.2-x86-linux
  * sass-embedded-1.64.2-x86-linux-android
  * sass-embedded-1.64.2-x86-linux-musl
  * sass-embedded-1.64.2-x86-mingw32
  * sass-embedded-1.64.2-x86_64-darwin
  * sass-embedded-1.64.2-x86_64-linux
  * sass-embedded-1.64.2-x86_64-linux-android
  * sass-embedded-1.64.2-x86_64-linux-musl
  * sass-embedded-1.66.0-aarch64-linux
  * sass-embedded-1.66.0-aarch64-linux-android
  * sass-embedded-1.66.0-aarch64-linux-musl
  * sass-embedded-1.66.0-arm-linux
  * sass-embedded-1.66.0-arm-linux-androideabi
  * sass-embedded-1.66.0-arm-linux-musleabihf
  * sass-embedded-1.66.0-arm64-darwin
  * sass-embedded-1.66.0
  * sass-embedded-1.66.0-x64-mingw-ucrt
  * sass-embedded-1.66.0-x64-mingw32
  * sass-embedded-1.66.0-x86-linux
  * sass-embedded-1.66.0-x86-linux-android
  * sass-embedded-1.66.0-x86-linux-musl
  * sass-embedded-1.66.0-x86-mingw32
  * sass-embedded-1.66.0-x86_64-darwin
  * sass-embedded-1.66.0-x86_64-linux
  * sass-embedded-1.66.0-x86_64-linux-android
  * sass-embedded-1.66.0-x86_64-linux-musl
  * sass-embedded-1.66.1-aarch64-linux
  * sass-embedded-1.66.1-aarch64-linux-android
  * sass-embedded-1.66.1-aarch64-linux-musl
  * sass-embedded-1.66.1-arm-linux
  * sass-embedded-1.66.1-arm-linux-androideabi
  * sass-embedded-1.66.1-arm-linux-musleabihf
  * sass-embedded-1.66.1-arm64-darwin
  * sass-embedded-1.66.1
  * sass-embedded-1.66.1-x64-mingw-ucrt
  * sass-embedded-1.66.1-x64-mingw32
  * sass-embedded-1.66.1-x86-linux
  * sass-embedded-1.66.1-x86-linux-android
  * sass-embedded-1.66.1-x86-linux-musl
  * sass-embedded-1.66.1-x86-mingw32
  * sass-embedded-1.66.1-x86_64-darwin
  * sass-embedded-1.66.1-x86_64-linux
  * sass-embedded-1.66.1-x86_64-linux-android
  * sass-embedded-1.66.1-x86_64-linux-musl
  * sass-embedded-1.67.0-aarch64-linux
  * sass-embedded-1.67.0-aarch64-linux-android
  * sass-embedded-1.67.0-aarch64-linux-musl
  * sass-embedded-1.67.0-arm-linux
  * sass-embedded-1.67.0-arm-linux-androideabi
  * sass-embedded-1.67.0-arm-linux-musleabihf
  * sass-embedded-1.67.0-arm64-darwin
  * sass-embedded-1.67.0
  * sass-embedded-1.67.0-x64-mingw-ucrt
  * sass-embedded-1.67.0-x64-mingw32
  * sass-embedded-1.67.0-x86-linux
  * sass-embedded-1.67.0-x86-linux-android
  * sass-embedded-1.67.0-x86-linux-musl
  * sass-embedded-1.67.0-x86-mingw32
  * sass-embedded-1.67.0-x86_64-darwin
  * sass-embedded-1.67.0-x86_64-linux
  * sass-embedded-1.67.0-x86_64-linux-android
  * sass-embedded-1.67.0-x86_64-linux-musl
  * sass-embedded-1.68.0-aarch64-linux
  * sass-embedded-1.68.0-aarch64-linux-android
  * sass-embedded-1.68.0-aarch64-linux-musl
  * sass-embedded-1.68.0-arm-linux
  * sass-embedded-1.68.0-arm-linux-androideabi
  * sass-embedded-1.68.0-arm-linux-musleabihf
  * sass-embedded-1.68.0-arm64-darwin
  * sass-embedded-1.68.0
  * sass-embedded-1.68.0-x64-mingw-ucrt
  * sass-embedded-1.68.0-x64-mingw32
  * sass-embedded-1.68.0-x86-linux
  * sass-embedded-1.68.0-x86-linux-android
  * sass-embedded-1.68.0-x86-linux-musl
  * sass-embedded-1.68.0-x86-mingw32
  * sass-embedded-1.68.0-x86_64-darwin
  * sass-embedded-1.68.0-x86_64-linux
  * sass-embedded-1.68.0-x86_64-linux-android
  * sass-embedded-1.68.0-x86_64-linux-musl
  * sass-embedded-1.69.1-aarch64-linux
  * sass-embedded-1.69.1-aarch64-linux-android
  * sass-embedded-1.69.1-aarch64-linux-musl
  * sass-embedded-1.69.1-arm-linux
  * sass-embedded-1.69.1-arm-linux-androideabi
  * sass-embedded-1.69.1-arm-linux-musleabihf
  * sass-embedded-1.69.1-arm64-darwin
  * sass-embedded-1.69.1
  * sass-embedded-1.69.1-x64-mingw-ucrt
  * sass-embedded-1.69.1-x64-mingw32
  * sass-embedded-1.69.1-x86-linux
  * sass-embedded-1.69.1-x86-linux-android
  * sass-embedded-1.69.1-x86-linux-musl
  * sass-embedded-1.69.1-x86-mingw32
  * sass-embedded-1.69.1-x86_64-darwin
  * sass-embedded-1.69.1-x86_64-linux
  * sass-embedded-1.69.1-x86_64-linux-android
  * sass-embedded-1.69.1-x86_64-linux-musl
  * sass-embedded-1.69.2-aarch64-linux
  * sass-embedded-1.69.2-aarch64-linux-android
  * sass-embedded-1.69.2-aarch64-linux-musl
  * sass-embedded-1.69.2-arm-linux
  * sass-embedded-1.69.2-arm-linux-androideabi
  * sass-embedded-1.69.2-arm-linux-musleabihf
  * sass-embedded-1.69.2-arm64-darwin
  * sass-embedded-1.69.2
  * sass-embedded-1.69.2-x64-mingw-ucrt
  * sass-embedded-1.69.2-x64-mingw32
  * sass-embedded-1.69.2-x86-linux
  * sass-embedded-1.69.2-x86-linux-android
  * sass-embedded-1.69.2-x86-linux-musl
  * sass-embedded-1.69.2-x86-mingw32
  * sass-embedded-1.69.2-x86_64-darwin
  * sass-embedded-1.69.2-x86_64-linux
  * sass-embedded-1.69.2-x86_64-linux-android
  * sass-embedded-1.69.2-x86_64-linux-musl
  * sass-embedded-1.69.3-aarch64-linux
  * sass-embedded-1.69.3-aarch64-linux-android
  * sass-embedded-1.69.3-aarch64-linux-musl
  * sass-embedded-1.69.3-arm-linux
  * sass-embedded-1.69.3-arm-linux-androideabi
  * sass-embedded-1.69.3-arm-linux-musleabihf
  * sass-embedded-1.69.3-arm64-darwin
  * sass-embedded-1.69.3
  * sass-embedded-1.69.3-x64-mingw-ucrt
  * sass-embedded-1.69.3-x64-mingw32
  * sass-embedded-1.69.3-x86-linux
  * sass-embedded-1.69.3-x86-linux-android
  * sass-embedded-1.69.3-x86-linux-musl
  * sass-embedded-1.69.3-x86-mingw32
  * sass-embedded-1.69.3-x86_64-darwin
  * sass-embedded-1.69.3-x86_64-linux
  * sass-embedded-1.69.3-x86_64-linux-android
  * sass-embedded-1.69.3-x86_64-linux-musl
  * sass-embedded-1.69.4-aarch64-linux
  * sass-embedded-1.69.4-aarch64-linux-android
  * sass-embedded-1.69.4-aarch64-linux-musl
  * sass-embedded-1.69.4-arm-linux
  * sass-embedded-1.69.4-arm-linux-androideabi
  * sass-embedded-1.69.4-arm-linux-musleabihf
  * sass-embedded-1.69.4-arm64-darwin
  * sass-embedded-1.69.4
  * sass-embedded-1.69.4-x64-mingw-ucrt
  * sass-embedded-1.69.4-x64-mingw32
  * sass-embedded-1.69.4-x86-linux
  * sass-embedded-1.69.4-x86-linux-android
  * sass-embedded-1.69.4-x86-linux-musl
  * sass-embedded-1.69.4-x86-mingw32
  * sass-embedded-1.69.4-x86_64-darwin
  * sass-embedded-1.69.4-x86_64-linux
  * sass-embedded-1.69.4-x86_64-linux-android
  * sass-embedded-1.69.4-x86_64-linux-musl
  * sass-embedded-1.69.5-aarch64-linux
  * sass-embedded-1.69.5-aarch64-linux-android
  * sass-embedded-1.69.5-aarch64-linux-musl
  * sass-embedded-1.69.5-arm-linux
  * sass-embedded-1.69.5-arm-linux-androideabi
  * sass-embedded-1.69.5-arm-linux-musleabihf
  * sass-embedded-1.69.5-arm64-darwin
  * sass-embedded-1.69.5
  * sass-embedded-1.69.5-x64-mingw-ucrt
  * sass-embedded-1.69.5-x64-mingw32
  * sass-embedded-1.69.5-x86-linux
  * sass-embedded-1.69.5-x86-linux-android
  * sass-embedded-1.69.5-x86-linux-musl
  * sass-embedded-1.69.5-x86-mingw32
  * sass-embedded-1.69.5-x86_64-darwin
  * sass-embedded-1.69.5-x86_64-linux
  * sass-embedded-1.69.5-x86_64-linux-android
  * sass-embedded-1.69.5-x86_64-linux-musl
  * sass-embedded-1.69.6-aarch64-linux
  * sass-embedded-1.69.6-aarch64-linux-android
  * sass-embedded-1.69.6-aarch64-linux-musl
  * sass-embedded-1.69.6-arm-linux
  * sass-embedded-1.69.6-arm-linux-androideabi
  * sass-embedded-1.69.6-arm-linux-musleabihf
  * sass-embedded-1.69.6-arm64-darwin
  * sass-embedded-1.69.6
  * sass-embedded-1.69.6-x64-mingw-ucrt
  * sass-embedded-1.69.6-x64-mingw32
  * sass-embedded-1.69.6-x86-linux
  * sass-embedded-1.69.6-x86-linux-android
  * sass-embedded-1.69.6-x86-linux-musl
  * sass-embedded-1.69.6-x86-mingw32
  * sass-embedded-1.69.6-x86_64-darwin
  * sass-embedded-1.69.6-x86_64-linux
  * sass-embedded-1.69.6-x86_64-linux-android
  * sass-embedded-1.69.6-x86_64-linux-musl
  * sass-embedded-1.69.7-aarch64-linux
  * sass-embedded-1.69.7-aarch64-linux-android
  * sass-embedded-1.69.7-aarch64-linux-musl
  * sass-embedded-1.69.7-arm-linux
  * sass-embedded-1.69.7-arm-linux-androideabi
  * sass-embedded-1.69.7-arm-linux-musleabihf
  * sass-embedded-1.69.7-arm64-darwin
  * sass-embedded-1.69.7
  * sass-embedded-1.69.7-x64-mingw-ucrt
  * sass-embedded-1.69.7-x64-mingw32
  * sass-embedded-1.69.7-x86-linux
  * sass-embedded-1.69.7-x86-linux-android
  * sass-embedded-1.69.7-x86-linux-musl
  * sass-embedded-1.69.7-x86-mingw32
  * sass-embedded-1.69.7-x86_64-darwin
  * sass-embedded-1.69.7-x86_64-linux
  * sass-embedded-1.69.7-x86_64-linux-android
  * sass-embedded-1.69.7-x86_64-linux-musl
  * sass-embedded-1.70.0-aarch64-linux
  * sass-embedded-1.70.0-aarch64-linux-android
  * sass-embedded-1.70.0-aarch64-linux-musl
  * sass-embedded-1.70.0-arm-linux
  * sass-embedded-1.70.0-arm-linux-androideabi
  * sass-embedded-1.70.0-arm-linux-musleabihf
  * sass-embedded-1.70.0-arm64-darwin
  * sass-embedded-1.70.0
  * sass-embedded-1.70.0-x64-mingw-ucrt
  * sass-embedded-1.70.0-x64-mingw32
  * sass-embedded-1.70.0-x86-linux
  * sass-embedded-1.70.0-x86-linux-android
  * sass-embedded-1.70.0-x86-linux-musl
  * sass-embedded-1.70.0-x86-mingw32
  * sass-embedded-1.70.0-x86_64-darwin
  * sass-embedded-1.70.0-x86_64-linux
  * sass-embedded-1.70.0-x86_64-linux-android
  * sass-embedded-1.70.0-x86_64-linux-musl

```

### Steps To Reproduce

Following the initial steps. This error happens when running `budle` for the first time within my folder. 
No changes done on my end.

I am using a Raspberry Pi (Debian)

```
ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux-gnu]

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) 


$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) 


$ make -v
GNU Make 4.3
Built for aarch64-unknown-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

### Expected Behavior

No errors, bundle install must not return errors

### Environment

- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux-gnu]

- Jekyll: $ bundle exec jekyll -v
Could not find gem 'jekyll-theme-chirpy (~> 6.3, >= 6.3.1)' in locally installed gems.
Run `bundle install` to install missing gems.

- Chirpy: $ bundle info jekyll-theme-chirpy
Could not find gem 'jekyll-theme-chirpy (~> 6.3, >= 6.3.1)' in locally installed
gems.

**Comment by bubl-ai** [comment]
After some checks, this seems to be a problem with the ruby and/or jekyll/bundler versions. This doesn't seem to be a problem with `jekyll-theme-chirpy `. Not sure what may be happening, this was working for me before.

**Comment by imagelessthought** [comment]
I encountered this error when I attempeted to rebuild my site with the latest Chirpy version.  I just went back through the install steps and installed all the prereqs and everything from scratch and the issue was resolved.  Basically it was a missed step somewhere.

**Comment by ivan-penchev** [comment]
I had something very similar as an error, there is certainly something flaky with this module.

My pipeline was originally set to run ruby/setup-ruby@v1
 with:
 ruby-version: 3
 that resulted in:
```
An error occurred while installing google-protobuf (3.25.2), and Bundler cannot
continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 6.5.0, which depends on
    jekyll-archives was resolved to 2.2.1, which depends on
      jekyll was resolved to 4.3.3, which depends on
        jekyll-sass-converter was resolved to 3.0.0, which depends on
          sass-embedded was resolved to 1.70.0, which depends on
            google-protobuf
```

I updated to ruby to 3.3 same stuff, but running it on 3.2 worked.

**Comment by lsilvam** [comment]
I am also getting the same error. 

It seems to me that the link is not correct:
> Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
underlying error <bad response Forbidden 403
(https://rubygems.org/gems/sass-embedded-1.71.0-x86_64-linux.gem)>

if you go to https://rubygems.org/gems/sass-embedded/versions `1.71.0-x86_64-linux` is not there

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/53966548/1478377d-e259-4e41-b4dc-f23277fc1f00)

hope it helps to solve this issue :)

**Comment by bubl-ai** [comment]
I am still having this issue and it is so frustrating. But I think it is unrelated to Chirpy as I also got the same error executing 'builder' in a different directory that doesn't have the Chirpy theme.

**Comment by bubl-ai** [comment]
@imagelessthought unfortunately it didn't work for me...

**Comment by bubl-ai** [comment]
@ivan-penchev I also think it is related to some incompatibility with the versions of the different dependencies. Can you include what versions you have for all the Jekyll dependencies?

**Comment by ntkme** [comment]
This is a known bug in older versions of rubygems. Please upgrade to ruby >=3.2, remove `Gemfile.lock`, and then it should work. See https://github.com/sass-contrib/sass-embedded-host-ruby/issues/176

For protobuf 3.25 issue, workaround is to add `rake` to your `Gemfile`. See https://github.com/protocolbuffers/protobuf/pull/15203

**Comment by cotes2020** [comment]
Duplicate of #1430
